### ISSUE TITLE
Compile failure w/ base-4.7

### ISSUE THREAD

**Issue by hvr** [fredefox/shade#1]
Welcome to Hackage!

I noticed you uploaded a series of `shade`  releases earlier today, as our [CI system](http://104.239.175.197:8080/package/shade) flagged them. Specifically all releases failed to build w/ GHC 7.8 / base-4.7, even though the cabal file specifically advertises compatiblity with `base >= 4.7 && < 5`.

```
Configuring component lib from shade-0.1.1.0...
Preprocessing library shade-0.1.1.0...
[1 of 1] Compiling Control.Monad.Shade ( src/Control/Monad/Shade.hs, /tmp/matrix-worker/1495226987/dist-newstyle/build/x86_64-linux/ghc-7.8.4/shade-0.1.1.0/build/Control/Monad/Shade.o )

src/Control/Monad/Shade.hs:29:27:
    Not in scope: type constructor or class ‘Applicative’

src/Control/Monad/Shade.hs:50:39:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Control.Monad)
```

whereas versions prior to `shade-0.1.0.3` also failed to compile with base-4.8:

```
Configuring component lib from shade-0.1.0.2...
Preprocessing library shade-0.1.0.2...
[1 of 1] Compiling Control.Monad.Shade ( src/Control/Monad/Shade.hs, /tmp/matrix-worker/1495225815/dist-newstyle/build/x86_64-linux/ghc-7.10.3/shade-0.1.0.2/build/Control/Monad/Shade.o )

Configuring component exe:shade from shade-0.1.0.2...
Warning: The package has a version range for a dependency on an internal library: shade -any && ==0.1.0.2. This version range has no semantic meaning and can be removed.
Preprocessing executable 'shade' for shade-0.1.0.2...
[1 of 1] Compiling Main             ( README.lhs, /tmp/matrix-worker/1495225815/dist-newstyle/build/x86_64-linux/ghc-7.10.3/shade-0.1.0.2/c/shade/build/shade/shade-tmp/Main.o )

README.lhs:42:22:
    No instance for (Monoid (IO ())) arising from a use of ‘mconcat’
    In the first argument of ‘(.)’, namely ‘mconcat’
    In the second argument of ‘(.)’, namely
      ‘mconcat . map (noisy . show)’
    In the second argument of ‘(.)’, namely
      ‘runInIO . mconcat . map (noisy . show)’
```

I've revised the meta-data of the affected release to reflect more accurate version bounds (that way the cabal solver can avoid picking those configurations which would result in a compile failure):

 - https://hackage.haskell.org/package/shade-shade-0.1.0.0/revisions/
 - https://hackage.haskell.org/package/shade-shade-0.1.0.1/revisions/
 - https://hackage.haskell.org/package/shade-shade-0.1.0.2/revisions/
 - https://hackage.haskell.org/package/shade-shade-0.1.0.3/revisions/
 - https://hackage.haskell.org/package/shade-shade-0.1.0.4/revisions/
 - https://hackage.haskell.org/package/shade-shade-0.1.1.0/revisions/

If you have any questions, please feel free to ask!

PS: I also noticed that the `description` ("Please see README.md") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

**Comment by hvr** [comment]
I just had to revise https://hackage.haskell.org/package/shade-0.1.1.1/revisions/ as well due to

```
Configuring component lib from shade-0.1.1.1...
Preprocessing library shade-0.1.1.1...
[1 of 1] Compiling Control.Monad.Shade ( src/Control/Monad/Shade.hs, /tmp/matrix-worker/1495307871/dist-newstyle/build/x86_64-linux/ghc-7.8.4/shade-0.1.1.1/build/Control/Monad/Shade.o )

src/Control/Monad/Shade.hs:63:39:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Control.Monad)
```
